### PR TITLE
Add generate option: -folder

### PR DESCRIPTION
**Pull request by MrGru**
Generate all file in folder with default information
packageName: folder name
varName: file name with underscore and extension

### CODE REVIEW

**Comment by hajimehoshi** [comment]
I'm against adding a directory path option. Wouldn't `-output` be enough?

**Comment by MrGru** [comment]
I think generate all files in folder is more convenient if we have a lot of files. We don't need to generate manually for each file

**Comment by hajimehoshi** [comment]
I am not sure what difference there is between specifying the path to `-output` and `-folder`.

**Comment by MrGru** [comment]
I only run `file2byteslice -folder` and all the files in current folder will be generate to .go file. I do not generate one by one file with specifying `-input` and `-output`

alt text

**Comment by hajimehoshi** [comment]
OK I understood what you would like to do. However, I still don't want to merge this CL: I'd like to keep `file2byteslice` 'dumb' as much as possible. You can make your own wrapper that uses `file2byteslice`.

**Pull request closed without merging**
